# Generated by Django 4.2.2 on 2023-06-21 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynotes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audionotes',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='audionotes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='videonotes',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='videonotes',
            name='user',
        ),
        migrations.AddField(
            model_name='notes',
            name='audionotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mynotes.audionotes'),
        ),
        migrations.AddField(
            model_name='notes',
            name='videonotes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mynotes.videonotes'),
        ),
    ]
